name: Daily Cloudflare Rebuild

on:
  schedule:
    # Runs at 6:00 AM UTC every day (9:00 AM Saudi time)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  trigger-cloudflare-rebuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: |
          # You need to set up a deploy hook in Cloudflare Pages dashboard
          # Go to your project settings > Build & deployments > Deploy hooks
          # Create a hook and add the URL as a GitHub secret CLOUDFLARE_DEPLOY_HOOK_URL
          
          if [ -n "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}" ]; then
            curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}"
            echo "✅ Cloudflare Pages rebuild triggered at $(date)"
          else
            echo "❌ CLOUDFLARE_DEPLOY_HOOK_URL secret not set"
            echo "Please add your Cloudflare deploy hook URL as a GitHub secret"
            exit 1
          fi